const express = require('express')
const {hasPermission} = require('./../middleware/authorization')
const router = express.Router()
const auth = require('./../middleware/auth')
const adminController = require('./../controllers/adminController')
router.get('/assigned-cv/:status', hasPermission('getCv'),adminController.getCv) 
router.patch('/recommendation/:_id',hasPermission('addAllRecommendation'),adminController.addAllRecommendation) 
router.get('/cv/:_id',hasPermission('getUserCv'), adminController.getUserCv) 
router.get('/detailedcv/:_id', hasPermission('getDetailedUserCv'),adminController.getDetailedUserCv) 
module.exports  = router